/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.Color;
import trainticketreservationsystem.Employee;

/**
 *
 * @author User
 */
public class AddEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployeeJPanel
     */
    public AddEmployeeJPanel() {
        initComponents();
        this.setSize(720, 630);

        RepeatedUserNamelabel.setVisible(true);
        Genderlabel.setVisible(true);
        RepeatedUserNamelabel.setVisible(true);
        TruejLabel.setVisible(true);

    }

    private void resetlabels() {
        PhonejLabel11.setText("");
        PasswordValidjLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TruejLabel = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AddressjTextField = new javax.swing.JTextField();
        UserNamejTextField = new javax.swing.JTextField();
        PhoneNumberjTextField = new javax.swing.JTextField();
        MalejRadioButton = new javax.swing.JRadioButton();
        FemalejRadioButton = new javax.swing.JRadioButton();
        AddEmployeejButton = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        QualificationsjComboBox = new javax.swing.JComboBox<>();
        PasswordValidjLabel = new javax.swing.JLabel();
        PhonejLabel11 = new javax.swing.JLabel();
        RepeatedUserNamelabel = new java.awt.Label();
        DOBjDateChooser = new com.toedter.calendar.JDateChooser();
        DOJjDateChooser = new com.toedter.calendar.JDateChooser();
        Genderlabel = new java.awt.Label();
        jLabel11 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(null);

        TruejLabel.setBackground(new java.awt.Color(243, 172, 172));
        TruejLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TruejLabel.setForeground(new java.awt.Color(0, 102, 0));
        add(TruejLabel);
        TruejLabel.setBounds(263, 19, 290, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel1.setText("User Name");
        add(jLabel1);
        jLabel1.setBounds(200, 103, 68, 15);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(200, 141, 61, 15);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        add(jLabel3);
        jLabel3.setBounds(200, 221, 52, 15);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number");
        add(jLabel5);
        jLabel5.setBounds(200, 259, 93, 15);

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel6.setText("Gender");
        add(jLabel6);
        jLabel6.setBounds(200, 291, 45, 15);

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel7.setText("Date Of Birth");
        add(jLabel7);
        jLabel7.setBounds(200, 334, 83, 15);

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel8.setText("Qualifications");
        add(jLabel8);
        jLabel8.setBounds(200, 372, 88, 15);

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel9.setText("Date Of Joining");
        add(jLabel9);
        jLabel9.setBounds(200, 408, 97, 15);

        AddressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextFieldActionPerformed(evt);
            }
        });
        add(AddressjTextField);
        AddressjTextField.setBounds(335, 219, 164, 20);

        UserNamejTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(UserNamejTextField);
        UserNamejTextField.setBounds(335, 103, 164, 20);
        add(PhoneNumberjTextField);
        PhoneNumberjTextField.setBounds(335, 257, 164, 20);

        MalejRadioButton.setBackground(new java.awt.Color(243, 172, 172));
        buttonGroup1.add(MalejRadioButton);
        MalejRadioButton.setText("Male");
        MalejRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MalejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalejRadioButtonActionPerformed(evt);
            }
        });
        add(MalejRadioButton);
        MalejRadioButton.setBounds(340, 290, 70, 23);

        FemalejRadioButton.setBackground(new java.awt.Color(243, 172, 172));
        buttonGroup1.add(FemalejRadioButton);
        FemalejRadioButton.setText("Female");
        FemalejRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FemalejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemalejRadioButtonActionPerformed(evt);
            }
        });
        add(FemalejRadioButton);
        FemalejRadioButton.setBounds(420, 290, 80, 23);

        AddEmployeejButton.setText("ADD");
        AddEmployeejButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeejButtonActionPerformed(evt);
            }
        });
        add(AddEmployeejButton);
        AddEmployeejButton.setBounds(370, 440, 70, 30);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        add(jPasswordField2);
        jPasswordField2.setBounds(335, 181, 164, 20);
        add(jPasswordField1);
        jPasswordField1.setBounds(335, 141, 164, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Confirm Password");
        add(jLabel4);
        jLabel4.setBounds(200, 183, 117, 15);

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel10.setText("Name");
        add(jLabel10);
        jLabel10.setBounds(200, 70, 35, 15);
        add(NamejTextField);
        NamejTextField.setBounds(335, 65, 164, 20);

        QualificationsjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fresh graduate", "experienced", "student" }));
        QualificationsjComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(QualificationsjComboBox);
        QualificationsjComboBox.setBounds(334, 370, 170, 20);

        PasswordValidjLabel.setForeground(new java.awt.Color(204, 51, 0));
        add(PasswordValidjLabel);
        PasswordValidjLabel.setBounds(509, 141, 185, 20);

        PhonejLabel11.setForeground(new java.awt.Color(204, 51, 0));
        add(PhonejLabel11);
        PhonejLabel11.setBounds(509, 257, 185, 20);

        RepeatedUserNamelabel.setBackground(new java.awt.Color(243, 172, 172));
        RepeatedUserNamelabel.setForeground(new java.awt.Color(153, 0, 0));
        add(RepeatedUserNamelabel);
        RepeatedUserNamelabel.setBounds(510, 100, 190, 20);
        add(DOBjDateChooser);
        DOBjDateChooser.setBounds(334, 329, 170, 20);
        add(DOJjDateChooser);
        DOJjDateChooser.setBounds(334, 408, 170, 20);

        Genderlabel.setBackground(new java.awt.Color(243, 172, 172));
        Genderlabel.setForeground(new java.awt.Color(153, 0, 0));
        add(Genderlabel);
        Genderlabel.setBounds(509, 291, 165, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/adminbackground.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 0, 720, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void AddressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextFieldActionPerformed

    private void FemalejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemalejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemalejRadioButtonActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void AddEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeejButtonActionPerformed
        // TODO add your handling code here:
        resetlabels();
        boolean flag = true;
        if (!NamejTextField.getText().equals("") && !UserNamejTextField.getText().equals("") && !jPasswordField1.getText().equals("") && !jPasswordField2.getText().equals("") && !AddressjTextField.getText().equals("") && !PhoneNumberjTextField.getText().equals("")) {
            // Gender , DOB , Date of joining .
            Employee x = new Employee();
            x.SetEmployeeName(NamejTextField.getText());
            x.SetUserName(UserNamejTextField.getText());

            if (jPasswordField1.getText().equals(jPasswordField2.getText())) {
                if (jPasswordField2.getText().length() > 8) {
                    x.SetPassWord(jPasswordField1.getText());
                } else {
                    PasswordValidjLabel.setText("password must be > 8 digits");
                    flag = false;
                }
            } else {
                PasswordValidjLabel.setText("Password doesn't match");
                flag = false;
            }

            x.SetEmployeeAddress(AddressjTextField.getText());

            if (PhoneNumberjTextField.getText().length() != 8) {
                PhonejLabel11.setText("not valid phone number (!=8)");
                flag = false;
            } else {
                x.SetEmployeePhoneNumber(Integer.parseInt(PhoneNumberjTextField.getText()));

            }

            if (MalejRadioButton.isSelected()) {
                x.SetEmployeeGender("Male");
            } else if (FemalejRadioButton.isSelected()) {
                x.SetEmployeeGender("Female");
            } else {
                flag = false;
                Genderlabel.setText("Gender !!");
                TruejLabel.setForeground(Color.red);
            }

            x.SetEmployeeDateOfBirth(DOBjDateChooser.getDate());

            if (QualificationsjComboBox.getSelectedItem().equals("fresh graduate")) {
                x.SetEmployeeQualifications("fresh graduate");
            } else if (QualificationsjComboBox.getSelectedItem().equals("experienced")) {
                x.SetEmployeeQualifications("experienced");
            } else if (QualificationsjComboBox.getSelectedItem().equals("student")) {
                x.SetEmployeeQualifications("student");
            }
            x.SetEmployeeDateOfJoining(DOJjDateChooser.getDate());

            if (x.repeatedUserName(UserNamejTextField.getText())) {
                RepeatedUserNamelabel.setForeground(Color.RED);
                RepeatedUserNamelabel.setText("Error : Repeated ID");
                flag = false;
            }

            if (!flag) {
                return;
            }
            if (x.AddEmployee()) {

                TruejLabel.setText("Employee added successfully !");
                resetPanelData();
                Genderlabel.setText("");

            } else {
                TruejLabel.setText("Failed to insert");
            }

        } else {
            TruejLabel.setText("Missing required Fields ... ! ");
        }


    }//GEN-LAST:event_AddEmployeejButtonActionPerformed

    private void MalejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MalejRadioButtonActionPerformed

    protected void resetPanelData() {
        NamejTextField.setText("");
        UserNamejTextField.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        PhoneNumberjTextField.setText("");
        AddressjTextField.setText("");
        QualificationsjComboBox.setSelectedIndex(0);
        RepeatedUserNamelabel.setText("");
        PasswordValidjLabel.setText("");
        PhonejLabel11.setText("");
        buttonGroup1.clearSelection();
        DOBjDateChooser = new com.toedter.calendar.JDateChooser();
        DOJjDateChooser = new com.toedter.calendar.JDateChooser();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeejButton;
    private javax.swing.JTextField AddressjTextField;
    private com.toedter.calendar.JDateChooser DOBjDateChooser;
    private com.toedter.calendar.JDateChooser DOJjDateChooser;
    private javax.swing.JRadioButton FemalejRadioButton;
    private java.awt.Label Genderlabel;
    private javax.swing.JRadioButton MalejRadioButton;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JLabel PasswordValidjLabel;
    private javax.swing.JTextField PhoneNumberjTextField;
    private javax.swing.JLabel PhonejLabel11;
    private javax.swing.JComboBox<String> QualificationsjComboBox;
    private java.awt.Label RepeatedUserNamelabel;
    private java.awt.Label TruejLabel;
    private javax.swing.JTextField UserNamejTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
