/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import trainticketreservationsystem.Employee;

/**
 *
 * @author welcome
 */
public final class ListEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListEmployeesJPanel
     */
    public ListEmployeesJPanel() {
        initComponents();
        this.setSize(700, 800);
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "Username", "Password", "address", "PhoneNumber", "gender", "DateOfBirth", "qualifications", "DateOfJoining"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[9];
        Employee emp = new Employee();

        ArrayList<Employee> Employees = emp.ListEmployees();

        Employees = emp.ListEmployees();

        for (Employee x : Employees) {
            rowData[0] = x.GetEmployeeName();
            rowData[1] = x.GetUserName();
            rowData[2] = x.GetPassWord();
            rowData[3] = x.GetEmployeeAddress();
            rowData[4] = x.GetEmployeePhoneNumber();
            rowData[5] = x.GetEmplyeeGender();
            Date date = x.GetEmployeeDateOfBirth();
            String dates= new SimpleDateFormat("dd MMM yyyy").format(date);
            rowData[6] = dates;
            rowData[7] = x.GetEmployeeQualifications();
            Date date1 = x.GetEmployeeDateOfJoining();
            rowData[8] = new SimpleDateFormat("dd MMM yyyy").format(date1);

            model.addRow(rowData);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
