/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.Color;
import trainticketreservationsystem.PDFFileManager;
import trainticketreservationsystem.Passenger;
import trainticketreservationsystem.Ticket;
import trainticketreservationsystem.Train;

/**
 *
 * @author welcome
 */
public class SearchTicketJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form SearchTicketJPanel
     */
    Ticket returned = new Ticket();

    public SearchTicketJPanel1() {
        initComponents();
        this.setSize(800, 700);
        this.setVisible(true);

    }

    protected void SetPanelData(Ticket t) {
        TicketNumberlabel.setText("" + t.GetTicketId());
        TrainIDlabel.setText("" + t.GetTrainId());
        BookedSeatlabel.setText("" + t.Getseats());
        Sourcelabel.setText("" + t.GetTripOriginPoint());
        Destinationlabel.setText("" + t.GetTripDestination());
        PassengerNamelabel.setText("" + t.GetPassengerName());
        MobileNumberlabel.setText("" + t.GetPassengerMobile());
        PassengerEmaillabel.setText("" + t.GetPassengerEmail());
    }

    protected void ResetPanelData() {
        TicketNumberlabel.setText("");
        TrainIDlabel.setText("");
        BookedSeatlabel.setText("");
        Sourcelabel.setText("");
        Destinationlabel.setText("");
        PassengerNamelabel.setText("");
        MobileNumberlabel.setText("");
        PassengerEmaillabel.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTicketjTextField = new javax.swing.JTextField();
        TicketNumberlabel = new java.awt.Label();
        TrainIDlabel = new java.awt.Label();
        BookedSeatlabel = new java.awt.Label();
        Sourcelabel = new java.awt.Label();
        Destinationlabel = new java.awt.Label();
        PassengerNamelabel = new java.awt.Label();
        MobileNumberlabel = new java.awt.Label();
        PassengerEmaillabel = new java.awt.Label();
        PrintjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();
        SearchTicketjButton = new javax.swing.JButton();
        Truelabel = new java.awt.Label();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label9 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label8 = new java.awt.Label();
        label7 = new java.awt.Label();
        label6 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchTicketjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTicketjTextFieldActionPerformed(evt);
            }
        });
        add(SearchTicketjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 270, 30));

        TicketNumberlabel.setBackground(new java.awt.Color(0, 135, 255));
        add(TicketNumberlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 40));

        TrainIDlabel.setBackground(new java.awt.Color(0, 135, 255));
        add(TrainIDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 180, 40));

        BookedSeatlabel.setBackground(new java.awt.Color(0, 135, 255));
        add(BookedSeatlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 180, 40));

        Sourcelabel.setBackground(new java.awt.Color(0, 135, 255));
        add(Sourcelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 180, 40));

        Destinationlabel.setBackground(new java.awt.Color(0, 135, 255));
        add(Destinationlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 180, 40));

        PassengerNamelabel.setBackground(new java.awt.Color(0, 135, 255));
        add(PassengerNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 180, 40));

        MobileNumberlabel.setBackground(new java.awt.Color(0, 135, 255));
        add(MobileNumberlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 180, 40));

        PassengerEmaillabel.setBackground(new java.awt.Color(0, 135, 255));
        add(PassengerEmaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 180, 40));

        PrintjButton.setText("PRINT");
        PrintjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintjButtonActionPerformed(evt);
            }
        });
        add(PrintjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 80, 40));

        CanceljButton.setText("CANCEL");
        CanceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButtonActionPerformed(evt);
            }
        });
        add(CanceljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 90, 40));

        SearchTicketjButton.setText("SEARCH");
        SearchTicketjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTicketjButtonActionPerformed(evt);
            }
        });
        add(SearchTicketjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, 30));

        Truelabel.setBackground(new java.awt.Color(0, 135, 255));
        add(Truelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 220, -1));

        label1.setBackground(new java.awt.Color(0, 135, 255));
        label1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 0, 0));
        label1.setText("Search by \"ticket number\"");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, 30));

        label2.setBackground(new java.awt.Color(0, 135, 255));
        label2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label2.setText("Ticket Number :");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, 40));

        label9.setBackground(new java.awt.Color(0, 135, 255));
        label9.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label9.setText("Train ID :");
        add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 40));

        label3.setBackground(new java.awt.Color(0, 135, 255));
        label3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label3.setText("Booked Seat :");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 110, 40));

        label4.setBackground(new java.awt.Color(0, 135, 255));
        label4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label4.setText("Source :");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 70, 40));

        label5.setBackground(new java.awt.Color(0, 135, 255));
        label5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label5.setText("Destination :");
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 100, 40));

        label8.setBackground(new java.awt.Color(0, 135, 255));
        label8.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label8.setText("Passenger Name :");
        add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 130, 40));

        label7.setBackground(new java.awt.Color(0, 135, 255));
        label7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label7.setText("Mobile Number :");
        add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 130, 40));

        label6.setBackground(new java.awt.Color(0, 135, 255));
        label6.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label6.setText("Passenger Email :");
        add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, 40));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/backgroundL.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTicketjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTicketjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTicketjTextFieldActionPerformed

    private void SearchTicketjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTicketjButtonActionPerformed
        // TODO add your handling code here:

        if (!SearchTicketjTextField.getText().equals("")) {
            returned = new Ticket();
            returned = returned.SearchByTicketID(Integer.parseInt(SearchTicketjTextField.getText()));

            if (!(returned.GetTicketId() == -1)) {
                SetPanelData(returned);
                Truelabel.setText("");
            } else {
                Truelabel.setText("Not Found ...!");
                Truelabel.setForeground(Color.red);
                SearchTicketjTextField.setText("");
                ResetPanelData();
            }

        } else {
            Truelabel.setText("Search by ticket number first !");
            return;
        }


    }//GEN-LAST:event_SearchTicketjButtonActionPerformed

    private void CanceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButtonActionPerformed
        // TODO add your handling code here:

        if (!SearchTicketjTextField.getText().equals("")) {
            Ticket t = new Ticket();
            if (t.RemoveTicket(Integer.parseInt(SearchTicketjTextField.getText()))) {
                Truelabel.setText("Deleted Successfully !");
                Truelabel.setForeground(Color.green);
                SearchTicketjTextField.setText("");
                ResetPanelData();
            } else {
                Truelabel.setText("Failed to delete !");
            }

        } else {
            Truelabel.setText("Search By ticket ID first !");
        }


    }//GEN-LAST:event_CanceljButtonActionPerformed

    private void PrintjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintjButtonActionPerformed
        // TODO add your handling code here:
       

        PDFFileManager.writePdf(TicketNumberlabel.getText(),
                TrainIDlabel.getText(), BookedSeatlabel.getText(),
                Sourcelabel.getText(), Destinationlabel.getText(),
                returned.trip.GetTripDate(), returned.trip.GetTripTime(), returned.Fare(Sourcelabel.getText(), Destinationlabel.getText())
        );

    }//GEN-LAST:event_PrintjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label BookedSeatlabel;
    private javax.swing.JButton CanceljButton;
    private java.awt.Label Destinationlabel;
    private java.awt.Label MobileNumberlabel;
    private java.awt.Label PassengerEmaillabel;
    private java.awt.Label PassengerNamelabel;
    private javax.swing.JButton PrintjButton;
    private javax.swing.JButton SearchTicketjButton;
    private javax.swing.JTextField SearchTicketjTextField;
    private java.awt.Label Sourcelabel;
    private java.awt.Label TicketNumberlabel;
    private java.awt.Label TrainIDlabel;
    private java.awt.Label Truelabel;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
