/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

/**
 *
 * @author User
 */
import java.awt.Color;
import trainticketreservationsystem.Employee;
import javax.swing.ButtonGroup;

public class SearchEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchEmployeeJPanel
     */
     ButtonGroup bg1 = new ButtonGroup();
    private void GroupButton() {

      
        bg1.add(MalejRadioButton);
        bg1.add(FemalejRadioButton);
    }

    public SearchEmployeeJPanel() {
        initComponents();
        GroupButton();
        this.setSize(700, 800);
        UserNamejTextField.setEditable(false);
        this.setSize(720, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    protected void SetPanelData(Employee x) {
        NamejTextField.setText("" + x.GetEmployeeName());
        UserNamejTextField.setText("" + x.GetUserName());

        if (x.GetEmplyeeGender().equals("Male")) {
            MalejRadioButton.setSelected(true);
            FemalejRadioButton.setSelected(false);
        } else {
            MalejRadioButton.setSelected(false);
            FemalejRadioButton.setSelected(true);
        }

        PasswordjTextField.setText("" + x.GetPassWord());
        AddressjTextField.setText("" + x.GetEmployeeAddress());
        PhoneNumberjTextField.setText("" + x.GetEmployeePhoneNumber());

        if (x.GetEmployeeQualifications().equals("fresh graduate")) {
            QualificationsjComboBox.setSelectedIndex(0);
        } else if (x.GetEmployeeQualifications().equals("experienced")) {
            QualificationsjComboBox.setSelectedIndex(1);
        } else if (x.GetEmployeeQualifications().equals("student")) {
            QualificationsjComboBox.setSelectedIndex(2);
        }
        DOBjDateChooser.setDate(x.GetEmployeeDateOfBirth());
        DOJjDateChooser.setDate(x.GetEmployeeDateOfJoining());
    }

    protected void ResetPanelData() {
        NamejTextField.setText("");
        UserNamejTextField.setText("");
        PasswordjTextField.setText("");
        PhoneNumberjTextField.setText("");
        AddressjTextField.setText("");
        bg1.clearSelection();
       

        DOBjDateChooser = new com.toedter.calendar.JDateChooser();
        DOJjDateChooser = new com.toedter.calendar.JDateChooser();
        QualificationsjComboBox.setSelectedIndex(0);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PhoneNumberjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MalejRadioButton = new javax.swing.JRadioButton();
        FemalejRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UserNamejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PasswordjTextField = new javax.swing.JTextField();
        SearchEmployeejTextField = new javax.swing.JTextField();
        SearchEmployeejButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        UpdatejButton = new javax.swing.JButton();
        AddressjTextField = new javax.swing.JTextField();
        DeletejButton = new javax.swing.JButton();
        DOBjDateChooser = new com.toedter.calendar.JDateChooser();
        DOJjDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        QualificationsjComboBox = new javax.swing.JComboBox<>();
        Truelabel = new java.awt.Label();
        PasswordValidjLabel = new java.awt.Label();
        PhonejLabel = new java.awt.Label();
        UserNamelabel = new java.awt.Label();
        BGjLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(169, 190, 61, 15);

        PhoneNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberjTextFieldActionPerformed(evt);
            }
        });
        add(PhoneNumberjTextField);
        PhoneNumberjTextField.setBounds(280, 266, 164, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        add(jLabel3);
        jLabel3.setBounds(169, 226, 52, 15);

        MalejRadioButton.setBackground(new java.awt.Color(243, 172, 172));
        MalejRadioButton.setText("Male");
        add(MalejRadioButton);
        MalejRadioButton.setBounds(280, 304, 60, 23);

        FemalejRadioButton.setBackground(new java.awt.Color(243, 172, 172));
        FemalejRadioButton.setText("Female");
        FemalejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemalejRadioButtonActionPerformed(evt);
            }
        });
        add(FemalejRadioButton);
        FemalejRadioButton.setBounds(345, 304, 80, 23);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number");
        add(jLabel5);
        jLabel5.setBounds(169, 268, 93, 15);

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel6.setText("Gender");
        add(jLabel6);
        jLabel6.setBounds(169, 307, 45, 15);

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel7.setText("Date Of Birth");
        add(jLabel7);
        jLabel7.setBounds(169, 347, 83, 15);

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel8.setText("Qualifications");
        add(jLabel8);
        jLabel8.setBounds(169, 385, 88, 15);

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel9.setText("Date Of Joining");
        add(jLabel9);
        jLabel9.setBounds(169, 430, 97, 15);

        UserNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamejTextFieldActionPerformed(evt);
            }
        });
        add(UserNamejTextField);
        UserNamejTextField.setBounds(280, 150, 164, 20);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel1.setText("UserName");
        add(jLabel1);
        jLabel1.setBounds(169, 150, 64, 15);
        add(PasswordjTextField);
        PasswordjTextField.setBounds(280, 188, 164, 20);

        SearchEmployeejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeejTextFieldActionPerformed(evt);
            }
        });
        add(SearchEmployeejTextField);
        SearchEmployeejTextField.setBounds(169, 43, 250, 20);

        SearchEmployeejButton.setText("SEARCH");
        SearchEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeejButtonActionPerformed(evt);
            }
        });
        add(SearchEmployeejButton);
        SearchEmployeejButton.setBounds(437, 42, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*Search by \"user name\" *");
        add(jLabel10);
        jLabel10.setBounds(169, 71, 118, 13);

        UpdatejButton.setText("UPDATE");
        UpdatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatejButtonActionPerformed(evt);
            }
        });
        add(UpdatejButton);
        UpdatejButton.setBounds(186, 459, 80, 30);

        AddressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextFieldActionPerformed(evt);
            }
        });
        add(AddressjTextField);
        AddressjTextField.setBounds(280, 228, 164, 20);

        DeletejButton.setText("DELETE");
        DeletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButtonActionPerformed(evt);
            }
        });
        add(DeletejButton);
        DeletejButton.setBounds(375, 459, 80, 30);
        add(DOBjDateChooser);
        DOBjDateChooser.setBounds(280, 340, 160, 20);
        add(DOJjDateChooser);
        DOJjDateChooser.setBounds(280, 430, 160, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Name");
        add(jLabel4);
        jLabel4.setBounds(169, 114, 35, 15);

        NamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamejTextFieldActionPerformed(evt);
            }
        });
        add(NamejTextField);
        NamejTextField.setBounds(280, 112, 164, 20);

        QualificationsjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fresh Graduate", "experienced", "student" }));
        add(QualificationsjComboBox);
        QualificationsjComboBox.setBounds(284, 383, 160, 20);

        Truelabel.setBackground(new java.awt.Color(243, 172, 172));
        Truelabel.setForeground(new java.awt.Color(204, 0, 51));
        add(Truelabel);
        Truelabel.setBounds(177, 12, 250, 20);

        PasswordValidjLabel.setBackground(new java.awt.Color(243, 172, 172));
        PasswordValidjLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(PasswordValidjLabel);
        PasswordValidjLabel.setBounds(454, 188, 215, 20);

        PhonejLabel.setBackground(new java.awt.Color(243, 172, 172));
        PhonejLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(PhonejLabel);
        PhonejLabel.setBounds(454, 266, 203, 20);

        UserNamelabel.setBackground(new java.awt.Color(243, 172, 172));
        UserNamelabel.setForeground(new java.awt.Color(204, 0, 0));
        add(UserNamelabel);
        UserNamelabel.setBounds(454, 150, 201, 20);

        BGjLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/adminbackground.png"))); // NOI18N
        add(BGjLabel1);
        BGjLabel1.setBounds(0, 0, 720, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberjTextFieldActionPerformed

    private void FemalejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemalejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemalejRadioButtonActionPerformed

    private void SearchEmployeejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmployeejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchEmployeejTextFieldActionPerformed

    private void AddressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextFieldActionPerformed

    private void UserNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamejTextFieldActionPerformed

    private void SearchEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmployeejButtonActionPerformed

        // TODO add your handling code here:
        if (!SearchEmployeejTextField.getText().equals("")) {
            Employee x = new Employee();
            Employee returned = x.SearchByEmployeeUserName(SearchEmployeejTextField.getText());
            if (returned.GetUserName() != null) {
                SetPanelData(returned);
                Truelabel.setText("");
            } else {
                Truelabel.setText("Not Found ...!");
                SearchEmployeejTextField.setText("");
                ResetPanelData();
            }
        } else {
            Truelabel.setText("Search by user name first !");
        }


    }//GEN-LAST:event_SearchEmployeejButtonActionPerformed

    private void UpdatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatejButtonActionPerformed
        // TODO add your handling code here:
        boolean flag = true;
        if (!UserNamejTextField.getText().equals("") && !PasswordjTextField.getText().equals("")
                && !AddressjTextField.getText().equals("") && !PhoneNumberjTextField.getText().equals("")) {

            Employee x = new Employee();
            x.SetEmployeeName(NamejTextField.getText());
            x.SetUserName(UserNamejTextField.getText());

            if (PasswordjTextField.getText().length() > 8) {
                x.SetPassWord(PasswordjTextField.getText());
                PasswordValidjLabel.setText("");
            } else {
                PasswordValidjLabel.setText("password must be > 8 digits");
                flag = false;
            }

            if (PhoneNumberjTextField.getText().length() != 8) {
                PhonejLabel.setText("not valid phone number (!=8)");
                flag = false;
            } else {
                x.SetEmployeePhoneNumber(Integer.parseInt(PhoneNumberjTextField.getText()));
                PhonejLabel.setText("");
            }
            if (MalejRadioButton.isSelected()) {
                x.SetEmployeeGender("Male");
            } else if (FemalejRadioButton.isSelected()) {
                x.SetEmployeeGender("Female");
            }
            x.SetEmployeeAddress(AddressjTextField.getText());
            x.SetEmployeeDateOfBirth(DOBjDateChooser.getDate());
            x.SetEmployeeDateOfJoining(DOJjDateChooser.getDate());
            if (QualificationsjComboBox.getSelectedItem().equals("fresh graduate")) {
                x.SetEmployeeQualifications("fresh graduate");
            } else if (QualificationsjComboBox.getSelectedItem().equals("experienced")) {
                x.SetEmployeeQualifications("experienced");
            } else if (QualificationsjComboBox.getSelectedItem().equals("student")) {
                x.SetEmployeeQualifications("student");
            }
            if (PasswordjTextField.getText().equals(PasswordjTextField.getText())) {
                x.SetPassWord(PasswordjTextField.getText());
            }
            if (!flag) {
                return;
            }

            if (x.UpdateEmployee()) {
                Truelabel.setText("Updated Successfully ... !");
                ResetPanelData();
                SearchEmployeejTextField.setText("");
            } else {
                Truelabel.setText("Failed to Update ... !");
            }
        } else {
            Truelabel.setText("Missing required Fields !");
        }


    }//GEN-LAST:event_UpdatejButtonActionPerformed

    private void DeletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButtonActionPerformed
        // TODO add your handling code here:
        if (!SearchEmployeejTextField.getText().equals("")) {
            Employee x = new Employee();
            if (x.DeleteEmployee((SearchEmployeejTextField.getText()))) {
                Truelabel.setText("Deleted Successfully ... !");
                ResetPanelData();
            } else {
                Truelabel.setText("Failed to delete ... !");
            }

        } else {
            Truelabel.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }

    }//GEN-LAST:event_DeletejButtonActionPerformed

    private void NamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamejTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressjTextField;
    private javax.swing.JLabel BGjLabel1;
    private com.toedter.calendar.JDateChooser DOBjDateChooser;
    private com.toedter.calendar.JDateChooser DOJjDateChooser;
    private javax.swing.JButton DeletejButton;
    private javax.swing.JRadioButton FemalejRadioButton;
    private javax.swing.JRadioButton MalejRadioButton;
    private javax.swing.JTextField NamejTextField;
    private java.awt.Label PasswordValidjLabel;
    private javax.swing.JTextField PasswordjTextField;
    private javax.swing.JTextField PhoneNumberjTextField;
    private java.awt.Label PhonejLabel;
    private javax.swing.JComboBox<String> QualificationsjComboBox;
    private javax.swing.JButton SearchEmployeejButton;
    private javax.swing.JTextField SearchEmployeejTextField;
    private java.awt.Label Truelabel;
    private javax.swing.JButton UpdatejButton;
    private javax.swing.JTextField UserNamejTextField;
    private java.awt.Label UserNamelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
