/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.util.Date;
import trainticketreservationsystem.*;

/**
 *
 * @author welcome
 */
public class SearchTrainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchTrainJPanel
     */
    public SearchTrainJPanel() {

        initComponents();
        this.setSize(720, 630);
        jTimeChooser.setShowSeconds(false);
        jTimeChooser.setShowIcon(true);
        TrainIDjTextField1.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrainIDjTextField1 = new javax.swing.JTextField();
        TrainNamejTextField2 = new javax.swing.JTextField();
        SearchTrainjButton = new javax.swing.JButton();
        SearchjTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UpdatejButton2 = new javax.swing.JButton();
        DeletejButton3 = new javax.swing.JButton();
        ErrorjLabel2 = new javax.swing.JLabel();
        DeletejLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTimeChooser = new lu.tudor.santec.jtimechooser.JTimeChooser();
        OriginPointjComboBox = new javax.swing.JComboBox<>();
        BGjLabel = new javax.swing.JLabel();

        setLayout(null);

        TrainIDjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainIDjTextField1ActionPerformed(evt);
            }
        });
        add(TrainIDjTextField1);
        TrainIDjTextField1.setBounds(301, 168, 164, 20);
        add(TrainNamejTextField2);
        TrainNamejTextField2.setBounds(301, 206, 164, 20);

        SearchTrainjButton.setText("SEARCH");
        SearchTrainjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTrainjButtonActionPerformed(evt);
            }
        });
        add(SearchTrainjButton);
        SearchTrainjButton.setBounds(464, 100, 90, 30);

        SearchjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjTextField5ActionPerformed(evt);
            }
        });
        add(SearchjTextField5);
        SearchjTextField5.setBounds(184, 101, 250, 20);

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel6.setText("Train ID");
        add(jLabel6);
        jLabel6.setBounds(173, 170, 52, 15);

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel7.setText("Train Name");
        add(jLabel7);
        jLabel7.setBounds(173, 208, 73, 15);

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel8.setText("Origin Point");
        add(jLabel8);
        jLabel8.setBounds(173, 241, 76, 15);

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel9.setText("Leaving Time");
        add(jLabel9);
        jLabel9.setBounds(173, 277, 83, 15);

        UpdatejButton2.setText("UPDATE");
        UpdatejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatejButton2ActionPerformed(evt);
            }
        });
        add(UpdatejButton2);
        UpdatejButton2.setBounds(225, 347, 80, 30);

        DeletejButton3.setText("DELETE");
        DeletejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletejButton3ActionPerformed(evt);
            }
        });
        add(DeletejButton3);
        DeletejButton3.setBounds(362, 347, 80, 30);

        ErrorjLabel2.setForeground(new java.awt.Color(153, 0, 0));
        add(ErrorjLabel2);
        ErrorjLabel2.setBounds(217, 45, 217, 25);

        DeletejLabel1.setForeground(new java.awt.Color(153, 0, 0));
        add(DeletejLabel1);
        DeletejLabel1.setBounds(243, 406, 170, 19);

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("*Search by \"ID\" *");
        add(jLabel1);
        jLabel1.setBounds(184, 129, 100, 14);
        add(jTimeChooser);
        jTimeChooser.setBounds(295, 277, 60, 30);

        OriginPointjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cairo", "Tanta", "Alexandria", "Minya", "Assuit" }));
        add(OriginPointjComboBox);
        OriginPointjComboBox.setBounds(301, 239, 164, 20);

        BGjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/adminbackground.png"))); // NOI18N
        add(BGjLabel);
        BGjLabel.setBounds(0, 0, 720, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void TrainIDjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainIDjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainIDjTextField1ActionPerformed

    private void SearchjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchjTextField5ActionPerformed

    private void SearchTrainjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTrainjButtonActionPerformed
        // TODO add your handling code here:
        if (!SearchjTextField5.getText().equals("")) {
            Train x = new Train();
            Train returned = (Train) x.SearchByTrainId(SearchjTextField5.getText());
            if (returned.GetTrainId() == null){
                ErrorjLabel2.setText("Not Found ...!");
                SearchjTextField5.setText("");
            
        }
             else 
               setPanelData(returned);
            
            
        } 
        else 
            ErrorjLabel2.setText("Search by train ID first");
        
    }

    protected void resetPanelData() {
        TrainIDjTextField1.setText("");
        TrainNamejTextField2.setText("");
        OriginPointjComboBox.setSelectedIndex(0);
        jTimeChooser=new lu.tudor.santec.jtimechooser.JTimeChooser();
        SearchjTextField5.setText("");
    }

    protected void setPanelData(Train x) {
        TrainIDjTextField1.setText("" + x.GetTrainId());
        TrainNamejTextField2.setText("" + x.GetTrainName());
        
        if (x.GetTrainOriginPoint().equals("Cairo")) {
            OriginPointjComboBox.setSelectedIndex(0);
        } else if (x.GetTrainOriginPoint().equals("Tanta")) {
            OriginPointjComboBox.setSelectedIndex(1);
        }
         else if (x.GetTrainOriginPoint().equals("Alexandria")) {
            OriginPointjComboBox.setSelectedIndex(2);
         }
        else if (x.GetTrainOriginPoint().equals("Minya")) {
            OriginPointjComboBox.setSelectedIndex(3);
         }
        else if (x.GetTrainOriginPoint().equals("Assuit")) {
            OriginPointjComboBox.setSelectedIndex(4);
         }
        
        jTimeChooser.setTime(x.GetTrainLeavingTime());

    }//GEN-LAST:event_SearchTrainjButtonActionPerformed

    private void DeletejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletejButton3ActionPerformed
        // TODO add your handling code here:
        if (!SearchjTextField5.getText().equals("")) {
            Train x = new Train();
            if (x.RemoveTrain(SearchjTextField5.getText())) {
                DeletejLabel1.setText("Deleted Successfully ... !");
                resetPanelData();
            } else {
                DeletejLabel1.setText("Failed to delete ... !");
            }
        } else {
            DeletejLabel1.setText("Missing required Fields");
        }
    }//GEN-LAST:event_DeletejButton3ActionPerformed

    private void UpdatejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatejButton2ActionPerformed
        // TODO add your handling code here:
        if (!TrainIDjTextField1.getText().equals("") && !TrainNamejTextField2.getText().equals("") ) {

            Train x = new Train();

            x.SetTrainId(TrainIDjTextField1.getText());
            x.SetTrainName(TrainNamejTextField2.getText()); 
            x.SetTrainOriginPoint((String) OriginPointjComboBox.getSelectedItem());
            Date temp=new Date();
            x.SetTrainLeavingTime(jTimeChooser.getDateWithTime(temp));

            if (x.UpdateTrain(x.GetTrainId())) {
                DeletejLabel1.setText("Updated Successfully ... !");
                resetPanelData();
            } else {
                DeletejLabel1.setText("Failed to Update ... !");
            }
        } else {
            DeletejLabel1.setText("Missing required Fields !");
        }
    }//GEN-LAST:event_UpdatejButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGjLabel;
    private javax.swing.JButton DeletejButton3;
    private javax.swing.JLabel DeletejLabel1;
    private javax.swing.JLabel ErrorjLabel2;
    private javax.swing.JComboBox<String> OriginPointjComboBox;
    private javax.swing.JButton SearchTrainjButton;
    private javax.swing.JTextField SearchjTextField5;
    private javax.swing.JTextField TrainIDjTextField1;
    private javax.swing.JTextField TrainNamejTextField2;
    private javax.swing.JButton UpdatejButton2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeChooser;
    // End of variables declaration//GEN-END:variables
}
