/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Panels.SearchTrainJPanel;
import Panels.*;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.*;
import trainticketreservationsystem.*;

/**
 *
 * @author welcome
 */
public class AdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrame
     */
    JPanel addE = new AddEmployeeJPanel();
    JPanel addT = new AddTrainJPanel();
    JPanel searchT = new SearchTrainJPanel();
    JPanel ListT = new ListTrainJPanel();
    JPanel ListE = new ListEmployeesJPanel();
    JPanel searchE = new SearchEmployeeJPanel();
    AudioThread a1 = new AudioThread("TrainWhistle.wav");
    
   
    public AdminJFrame() {
        a1.start();
        try {
            sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(AdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        a1.running = false;
        initComponents();
        this.add(addE);
        this.add(addT);
        this.add(searchT);
        this.add(ListT);
        this.add(ListE);
        this.add(searchE);
        this.addT.setVisible(false);
        this.addE.setVisible(false);
        this.searchT.setVisible(false);
        this.ListT.setVisible(false);
        this.ListE.setVisible(false);
        this.searchE.setVisible(false);
        this.BackjButton.setVisible(false);
        setTitle("Admin");
         this.setSize(700, 580); 
         this.setResizable(false);
    }

    private void HideButtons() {
        this.AddEmployeejLabel.setVisible(false);
        this.AddTrainjLabel.setVisible(false);
        this.ListEmployeesjLabel.setVisible(false);
        this.ListTrainsjLabel.setVisible(false);
        this.SearchEmployeejLabel.setVisible(false);
        this.SearchTrainjLabel.setVisible(false);
        this.BGjLabel.setVisible(false);
    }

    private void ShowButtons() {
        this.AddEmployeejLabel.setVisible(true);
        this.AddTrainjLabel.setVisible(true);
        this.ListEmployeesjLabel.setVisible(true);
        this.ListTrainsjLabel.setVisible(true);
        this.SearchEmployeejLabel.setVisible(true);
        this.SearchTrainjLabel.setVisible(true);
        this.BGjLabel.setVisible(true);
    }

    private void HidePanels() {
        this.addE.setVisible(false);
        this.addT.setVisible(false);
        this.searchT.setVisible(false);
        this.ListT.setVisible(false);
        this.ListE.setVisible(false);
        this.searchE.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEmployeejLabel = new javax.swing.JLabel();
        SearchEmployeejLabel = new javax.swing.JLabel();
        ListEmployeesjLabel = new javax.swing.JLabel();
        AddTrainjLabel = new javax.swing.JLabel();
        ListTrainsjLabel = new javax.swing.JLabel();
        SearchTrainjLabel = new javax.swing.JLabel();
        BackjButton = new javax.swing.JButton();
        BGjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AddEmployeejLabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        AddEmployeejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/add_employee1.png"))); // NOI18N
        AddEmployeejLabel.setText("Add Employee");
        AddEmployeejLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEmployeejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEmployeejLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddEmployeejLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddEmployeejLabelMouseExited(evt);
            }
        });
        getContentPane().add(AddEmployeejLabel);
        AddEmployeejLabel.setBounds(171, 171, 151, 45);

        SearchEmployeejLabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        SearchEmployeejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/update_employee1.png"))); // NOI18N
        SearchEmployeejLabel.setText("Search  Employee");
        SearchEmployeejLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchEmployeejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchEmployeejLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchEmployeejLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchEmployeejLabelMouseExited(evt);
            }
        });
        getContentPane().add(SearchEmployeejLabel);
        SearchEmployeejLabel.setBounds(171, 241, 172, 45);

        ListEmployeesjLabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ListEmployeesjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/list_employees1.png"))); // NOI18N
        ListEmployeesjLabel.setText("List Employees");
        ListEmployeesjLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListEmployeesjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListEmployeesjLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListEmployeesjLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListEmployeesjLabelMouseExited(evt);
            }
        });
        getContentPane().add(ListEmployeesjLabel);
        ListEmployeesjLabel.setBounds(171, 313, 156, 45);

        AddTrainjLabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        AddTrainjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/add_train1.png"))); // NOI18N
        AddTrainjLabel.setText("Add Train");
        AddTrainjLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTrainjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTrainjLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddTrainjLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddTrainjLabelMouseExited(evt);
            }
        });
        getContentPane().add(AddTrainjLabel);
        AddTrainjLabel.setBounds(381, 171, 125, 45);

        ListTrainsjLabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ListTrainsjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/list_train1.png"))); // NOI18N
        ListTrainsjLabel.setText("List Trains");
        ListTrainsjLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListTrainsjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListTrainsjLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListTrainsjLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListTrainsjLabelMouseExited(evt);
            }
        });
        getContentPane().add(ListTrainsjLabel);
        ListTrainsjLabel.setBounds(381, 313, 130, 45);

        SearchTrainjLabel.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        SearchTrainjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/update_train1.png"))); // NOI18N
        SearchTrainjLabel.setText("Search Train");
        SearchTrainjLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchTrainjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTrainjLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchTrainjLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchTrainjLabelMouseExited(evt);
            }
        });
        getContentPane().add(SearchTrainjLabel);
        SearchTrainjLabel.setBounds(381, 241, 142, 45);

        BackjButton.setText("Back");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackjButton);
        BackjButton.setBounds(10, 520, 70, 30);

        BGjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/adminbackground.png"))); // NOI18N
        getContentPane().add(BGjLabel);
        BGjLabel.setBounds(0, 0, 720, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    *
     *
     *
     *
     *
     * Click actions
     *
     *
     *
     */

    private void AddEmployeejLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmployeejLabelMouseClicked
        // TODO add your handling code here:
        HideButtons();
        this.addE.setVisible(true);
        this.BackjButton.setVisible(true);
    }//GEN-LAST:event_AddEmployeejLabelMouseClicked

    private void AddTrainjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTrainjLabelMouseClicked
        // TODO add your handling code here:
        HideButtons();
        this.addT.setVisible(true);
        this.BackjButton.setVisible(true);
    }//GEN-LAST:event_AddTrainjLabelMouseClicked

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
        HidePanels();
        ShowButtons();
        addE = new AddEmployeeJPanel();
        addT = new AddTrainJPanel();
        searchT = new SearchTrainJPanel();
        ListT = new ListTrainJPanel();
        ListE = new ListEmployeesJPanel();
        searchE = new SearchEmployeeJPanel();
        this.add(addT);
        this.add(searchT);
        this.add(ListT);
        this.add(ListE);
        this.add(searchE);
        this.add(addE);
        this.addT.setVisible(false);
        this.addE.setVisible(false);
        this.searchT.setVisible(false);
        this.ListT.setVisible(false);
        this.ListE.setVisible(false);
        this.searchE.setVisible(false);
        this.BackjButton.setVisible(false);
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void SearchTrainjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTrainjLabelMouseClicked
        // TODO add your handling code here:
        HideButtons();
        this.searchT.setVisible(true);
        this.BackjButton.setVisible(true);
    }//GEN-LAST:event_SearchTrainjLabelMouseClicked

    private void ListTrainsjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTrainsjLabelMouseClicked
        // TODO add your handling code here:
        HideButtons();
        this.ListT.setVisible(true);
        this.BackjButton.setVisible(true);
    }//GEN-LAST:event_ListTrainsjLabelMouseClicked

    /*
    *
    *
    *
    Hover Borders 
    *
    *
    *
    */
                                             

    private void AddEmployeejLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmployeejLabelMouseEntered
        // TODO add your handling code here:
        //AddEmployeejLabel.setBorder(loweredBevel);
        AddEmployeejLabel.setForeground(Color.red);
    }//GEN-LAST:event_AddEmployeejLabelMouseEntered

    private void AddEmployeejLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmployeejLabelMouseExited
        // TODO add your handling code here:
        //AddEmployeejLabel.setBorder(empty);
        AddEmployeejLabel.setForeground(Color.black);
    }//GEN-LAST:event_AddEmployeejLabelMouseExited

    private void AddTrainjLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTrainjLabelMouseEntered
        // TODO add your handling code here:
        //AddEmployeejLabel.setBorder(loweredBevel);
        AddTrainjLabel.setForeground(Color.red);
    }//GEN-LAST:event_AddTrainjLabelMouseEntered

    private void AddTrainjLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTrainjLabelMouseExited
        // TODO add your handling code here:
        //AddEmployeejLabel.setBorder(empty);
        AddTrainjLabel.setForeground(Color.black);
    }//GEN-LAST:event_AddTrainjLabelMouseExited

    private void ListEmployeesjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListEmployeesjLabelMouseClicked
        // TODO add your handling code here:
        HideButtons();
        this.ListE.setVisible(true);
        this.BackjButton.setVisible(true);

    }//GEN-LAST:event_ListEmployeesjLabelMouseClicked

    private void SearchEmployeejLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEmployeejLabelMouseClicked
        // TODO add your handling code here:
        HideButtons();
        this.searchE.setVisible(true);
        this.BackjButton.setVisible(true);
    }//GEN-LAST:event_SearchEmployeejLabelMouseClicked

    private void ListEmployeesjLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListEmployeesjLabelMouseEntered
        // TODO add your handling code here:
        ListEmployeesjLabel.setForeground(Color.red);
    }//GEN-LAST:event_ListEmployeesjLabelMouseEntered

    private void SearchEmployeejLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEmployeejLabelMouseEntered
        // TODO add your handling code here:
        SearchEmployeejLabel.setForeground(Color.red);
    }//GEN-LAST:event_SearchEmployeejLabelMouseEntered

    private void SearchTrainjLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTrainjLabelMouseEntered
        // TODO add your handling code here:
        SearchTrainjLabel.setForeground(Color.red);
    }//GEN-LAST:event_SearchTrainjLabelMouseEntered

    private void ListTrainsjLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTrainsjLabelMouseEntered
        // TODO add your handling code here:
        ListTrainsjLabel.setForeground(Color.red);
    }//GEN-LAST:event_ListTrainsjLabelMouseEntered

    private void SearchEmployeejLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEmployeejLabelMouseExited
        // TODO add your handling code here:
        SearchEmployeejLabel.setForeground(Color.black);
    }//GEN-LAST:event_SearchEmployeejLabelMouseExited

    private void ListEmployeesjLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListEmployeesjLabelMouseExited
        // TODO add your handling code here:
        ListEmployeesjLabel.setForeground(Color.black);
    }//GEN-LAST:event_ListEmployeesjLabelMouseExited

    private void SearchTrainjLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTrainjLabelMouseExited
        // TODO add your handling code here:
        SearchTrainjLabel.setForeground(Color.black);
    }//GEN-LAST:event_SearchTrainjLabelMouseExited

    private void ListTrainsjLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListTrainsjLabelMouseExited
        // TODO add your handling code here:
        ListTrainsjLabel.setForeground(Color.black);
    }//GEN-LAST:event_ListTrainsjLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddEmployeejLabel;
    private javax.swing.JLabel AddTrainjLabel;
    private javax.swing.JLabel BGjLabel;
    private javax.swing.JButton BackjButton;
    private javax.swing.JLabel ListEmployeesjLabel;
    private javax.swing.JLabel ListTrainsjLabel;
    private javax.swing.JLabel SearchEmployeejLabel;
    private javax.swing.JLabel SearchTrainjLabel;
    // End of variables declaration//GEN-END:variables
}
