/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JPanel;
import Panels.*;
import trainticketreservationsystem.Trips;

/**
 *
 * @author welcome
 */
public class EmployeeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeJFrame
     */
    JPanel res = new reservation();
    JPanel search = new SearchTicketJPanel1();

    public EmployeeJFrame() {
        initComponents();
        this.add(res);
        this.add(search);
        this.BackjLabel.setVisible(false);
        this.res.setVisible(false);
        search.setVisible(false);
        this.setSize(800, 700);
        this.doLayout();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DestinationjComboBox = new javax.swing.JComboBox<>();
        SourcejComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Truelabel = new java.awt.Label();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        BackjLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        DestinationjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cairo", "Tanta", "Alexandria", "Minya", "Assuit" }));
        getContentPane().add(DestinationjComboBox);
        DestinationjComboBox.setBounds(580, 120, 85, 20);

        SourcejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cairo", "Tanta", "Alexandria", "Minya", "Assuit" }));
        SourcejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcejComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SourcejComboBox);
        SourcejComboBox.setBounds(280, 120, 76, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setText("Destination");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 120, 73, 15);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("Source");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 120, 43, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/taindetail.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 390, 101, 116);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ManageTickets.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 400, 104, 94);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel5.setText("Calender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 250, 56, 15);

        Truelabel.setBackground(new java.awt.Color(0, 135, 255));
        Truelabel.setMaximumSize(new java.awt.Dimension(4, 20));
        getContentPane().add(Truelabel);
        Truelabel.setBounds(350, 70, 220, 20);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(340, 240, 180, 30);

        BackjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/arrow.png"))); // NOI18N
        BackjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelMouseClicked(evt);
            }
        });
        getContentPane().add(BackjLabel);
        BackjLabel.setBounds(30, 510, 80, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panels/Images/backgroundL.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void HideButtons() {
        this.jLabel5.setVisible(false);
        this.DestinationjComboBox.setVisible(false);
        this.SourcejComboBox.setVisible(false);
        this.jLabel1.setVisible(false);
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jDateChooser1.setVisible(false);
    }

    private void HidePanels() {
        this.res.setVisible(false);
        this.search.setVisible(false);
    }

    private void ShowButtons() {
        this.jLabel5.setVisible(true);
        this.DestinationjComboBox.setVisible(true);
        this.SourcejComboBox.setVisible(true);
        this.jLabel1.setVisible(true);
        this.jLabel2.setVisible(true);
        this.jLabel3.setVisible(true);
        this.jLabel4.setVisible(true);
        this.jDateChooser1.setVisible(true);
        this.jLabel6.setVisible(true);
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        boolean flag = true;

        Trips x = new Trips();
        if (SourcejComboBox.getSelectedItem() != DestinationjComboBox.getSelectedItem()) {
            if (SourcejComboBox.getSelectedItem().equals("Cairo")) {
                x.SetTripOriginPoint("Cairo");
            } else if (SourcejComboBox.getSelectedItem().equals("Alexandria")) {
                x.SetTripOriginPoint("Alexandria");
            } else if (SourcejComboBox.getSelectedItem().equals("Tanta")) {
                x.SetTripOriginPoint("Tanta");
            } else if (SourcejComboBox.getSelectedItem().equals("Minya")) {
                x.SetTripOriginPoint("Minya");
            }
            if (SourcejComboBox.getSelectedItem().equals("Assuit")) {
                x.SetTripOriginPoint("Assuit");
            }
            if (DestinationjComboBox.getSelectedItem().equals("Cairo")) {
                x.SetTripDestination("Cairo");
            } else if (DestinationjComboBox.getSelectedItem().equals("Alexandria")) {
                x.SetTripDestination("Alexandria");
            } else if (DestinationjComboBox.getSelectedItem().equals("Tanta")) {
                x.SetTripDestination("Tanta");
            } else if (DestinationjComboBox.getSelectedItem().equals("Minya")) {
                x.SetTripDestination("Minya");
            } else if (DestinationjComboBox.getSelectedItem().equals("Assuit")) {
                x.SetTripDestination("Assuit");
            }

        } else {
            Truelabel.setText("Choose another city");
            flag = false;

        }
        x.SetTripDate(jDateChooser1.getDate());
        if (!flag) {
            return;
        } else {

            HideButtons();
            String d = (String) SourcejComboBox.getSelectedItem();
            this.res = new reservation(x);
            this.add(res);
            this.res.setVisible(true);
            this.BackjLabel.setVisible(true);
            Truelabel.setVisible(false);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        HideButtons();
        BackjLabel.setVisible(true);
        this.search.setVisible(true);

    }//GEN-LAST:event_jLabel4MouseClicked

    private void BackjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelMouseClicked
        // TODO add your handling code here:
        HidePanels();
        ShowButtons();
        BackjLabel.setVisible(false);
    }//GEN-LAST:event_BackjLabelMouseClicked

    private void SourcejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcejComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SourcejComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackjLabel;
    private javax.swing.JComboBox<String> DestinationjComboBox;
    private javax.swing.JComboBox<String> SourcejComboBox;
    private java.awt.Label Truelabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
